import type { Metadata } from "next";
import Link from "next/link";
import { requireFirm } from "@/lib/auth/session";
import { PageHeader } from "@/components/layout/page-header";
import { LegalReviewNotice } from "@/components/legal-review-notice";

export const metadata: Metadata = {
  title: "New agreement",
};

export default async function NewAgreementPage() {
  await requireFirm();

  return (
    <div className="space-y-8">
      <PageHeader
        title="New costs agreement"
        description="The costs agreement wizard is not part of this foundation."
      />
      <LegalReviewNotice />
      <p className="max-w-2xl text-sm leading-6 text-ink-muted">
        Agreements will later be assembled from an approved template, jurisdiction,
        structured matter data, firm details, client details and pricing. Legal
        wording is not generated by an LLM, and nothing in this product is yet
        approved legal drafting.
      </p>
      <Link
        href="/agreements"
        className="inline-flex h-10 items-center border border-rule-strong bg-paper-raised px-4 text-sm font-medium"
      >
        Back to agreements
      </Link>
    </div>
  );
}
